config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :bookings do
    member do
      get :owner_revenue
    end
  end
  resources :invoices do
    collection do
      get :unpaid
    end
  end

  namespace :admin do
    resources :landing_users
    resources :feedbacks
    resources :robots do
      member do 
        get :config_tasks
      end
    end
    resources :robot_tasks
    resources :approvals
    resources :feishu_objects do
      member do 
        get :config_tasks
      end
    end
  end

  %w(
    forbidden
    compare_invoices 
    compare_journal_entries
    feishu_auth
    feishu_auth_from_external
    jira_dashboard
  ).each do |a|
    get a => "home##{a}"
  end
  
  %w(
    daily_incomes_overview
    deposits_overview
    houses_overview
    bookings_overview
    journal_entries_overview
    invoices_overview
    ar_overdue_summary
  ).each do |a|
    get a => "statistics##{a}"
  end

  %w(
    extensions
  ).each do |a|
    get a => "auto_checks##{a}"
  end

  post "/salesforce/:klass" => "home#salesforce_hook"

  get "houses_stas/:id" => "statistics#house_detail"
  get "ar_overdue_summary/:obj_id" => "statistics#ar_overdue_detail"
  get "month_overview" => "daily_incomes#month_overview"
  get "auth/:session_key" => "home#auth"
  post "feishu_events" => "home#feishu_events"
  post "ai_events" => "home#ai_events"
  post "jira_events" => "home#jira_events"
  get "jira_events" => "home#jira_events"
  get "big_screen_data" => "home#big_screen_data"
  post "bitbucket_events" => "home#bitbucket_events"
  post "rocket_chats" => "home#rocket_chats"
  get "houses/:id/coordinate" => "houses#coordinate"
  post "gmail" => "home#gmail_hook"

  require 'sidekiq/web'
  require 'sidekiq/cron/web'
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq_finance', :constraints => AdminConstraint.new
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  before_action :auth_user, only: [:index, :compare_journal_entries, :compare_invoices]
  before_action :verify_authenticity_token, only: [:index, :compare_journal_entries, :compare_invoices]
  before_action :get_basic_data
  before_action :get_finance_data
  before_action :base_compare_params, only: [:compare_invoices, :compare_journal_entries]

  def index
    @invoice_total = RedisHelper.get("Invoice:total_amounts")
    @invoice_cache = Invoice.global_cache
    @deposit_cache = Deposit.global_cache
  end

  def compare_journal_entries
    @pms_jes = JournalEntry.where(payment_id: @pms_invoice_ids)
    @qb_jes = QbObject.for_journal_entries.where(local_value: @pms_jes.map(&:journal_no).uniq)
  end

  def compare_invoices
    @qb_invoices = QbObject.for_invoice.where(local_value: @pms_invoice_ids)
  end

  def auth
    if current_user = User.auth_from_pms(params[:session_key])
      session[:user_id] = current_user.id
    end
    rpath = root_path
    rpath = session[:return_to] if session[:return_to] && !session[:return_to].in?(root_path) &&
      session[:return_to].to_s !~ /^\/auth/
    session[:return_to] = nil
    redirect_to rpath
  end

  def forbidden
    redirect_to PMS_ENDPOINT + "/new_financial_system", allow_other_host: true
  end

  def feishu_events
    params.permit!
    LarkEventWorker.perform_async(params.to_json)
    render json: {challenge: params[:challenge]}
  end

  def ai_events
    params.permit!
    AiEventWorker.perform_async(params.to_json)
    render json: {challenge: params[:challenge]}
  end

  def jira_events 
    params.permit!
    JiraIssuesWorker.perform_async(params.to_json)
    render json: {result: "succuess"}
  end

  def bitbucket_events
    params.permit!
    BitbucketWorker.perform_async(params.to_json)
    render json: {result: "succuess"}
  end

  def feishu_auth_from_external
    return to_feishu_auth_url(params[:source]) if !session[:lark_open_id].present? && !current_user

    lark_user = current_user&.feishu_user || FeishuObject.find_user_with(session[:lark_open_id])
    back_to_third_system(lark_user, params[:source])
  end

  def feishu_auth
    oid = session[:lark_open_id]
    fetch_lark_user(oid, params[:state]).presence and return

    if remote_code = params[:code]
      user_info = lark_app.request_feishu_user_info(remote_code) || {}
      oid = session[:lark_open_id] = user_info["open_id"]
    end
    oid.nil? || !lark_app.logined_user?(oid) and return to_feishu_auth_url
    fetch_lark_user(oid, params[:state])
  end

  def redirect_after_feishu_user_authed(feishu_user, state)
    back_to_third_system(@lark_user, state) if state != 'state'
  end

  def salesforce_hook
    Rails.logger.info(params.to_json)
    RedisHelper.lpush("salesforce_hooked_data", params.to_json)
  end

  def gmail_hook
    Rails.logger.info(params.to_json)
    case params["type"]
    when "services"
      msg_card = {
        header: "Service Gmail Received a New Email",
        template: "grey",
        elements: [
          { fields: { From: params["sender"], Time: params["datetime"], Subject: params["subject"], Link: params['url'] }}
        ]
      }
      LarkMsg.enqueue(:service_gmail_alarm, msg_card)
    else
    end
    render json: { result: "success" }
  end

  def big_screen_data
    json = RedisHelper.get_json("BigScreenData")
    json["unoccupied_list"] = json["unoccupied_list"].select{|a| a["active"]}.sort_by{|a| a["since"] || Date.current.to_s}
    json["orders_list"] = json["orders_list"].map do |a| 
      a["display_amount"] = PmsRecord.to_currency(a[:total_amount].to_f)
      a
    end
    %w(rental expense occ adr revpar revpar_bar cpor cpar).each do |a|
      val = a == 'occ' ? json[a].to_f * 100 : json[a].to_f
      json[a] = [{value: val}]
    end
    ws = json.delete("workorders")
    %w(overdue ongoing total finished).each do |a|
      json["workorders_#{a}"] = [{value: ws[a]}]
    end

    render json: json[params[:key]] || json
  end

  def rocket_chats
    Rails.logger.info(params.to_json)
    # msg = "#{params["user_name"]}: #{params["text"]}"
    msgs = params.dig("messages").presence || []
    if msg = msgs.first
      uname = msg.dig("u", "name") ||  msg.dig("u", "username")
      content = msg.dig("msg")
      LarkMsg.enqueue(:rocket_chats, header: 'New RocketChat Msg', elements: ["#{uname}: #{content}"])
    end
    render json: {result: "succuess"}
  end

  def jira_dashboard
    @tasks = JiraTask.current_month
    @tasks = JiraTask.last(100) if Rails.env.development?
    render layout: false
  end

  private

  def back_to_third_system(lark_user, source)
    url = URI(source)
    lark_token = SecureRandom.uuid
    RedisHelper.cache!("LarkToken-#{lark_token}", lark_user&.pms_user&.id) rescue nil

    origin_site = [url.scheme, [url.host, url.port].join(":")].join("://")
    callback = origin_site + "/auth_from_lark"
    callback = "#{callback}?lark_token=#{lark_token}&source=#{url}"
    redirect_to callback, allow_other_host: true
  end

  def fetch_lark_user(oid, state)
    if lark_user_info = lark_app.get_cached_user_info(oid).presence
      @lark_user = FeishuObject.find_user_with lark_user_info[:open_id]
      return redirect_after_feishu_user_authed(@lark_user, state) if @lark_user
    end
  end

  def to_feishu_auth_url(state = 'state', redirect_uri = nil)
    redirect_to(lark_app.auth_url(redirect_uri, state), allow_other_host: true)
  end

  def base_compare_params
    @filter_columns = %w(period)
    # @period_column = "finance_create_at"
    @base_invoices = Invoice.compared_period_in(@period)
    @pms_invoice_ids = @base_invoices.map(&:id)
  end

  def lark_app
    @lark_app ||= LarkApp.inner_tool
  end
end

app/views/home/compare_invoices.html.slim
- pms_size = @pms_invoice_ids.size
- qb_size = @qb_invoices.size
.main-content
  .left-panel style="width: 35%"
    h3 Compares Summary
    table class=table_base_class 
      tr.theader
        td Revenue Clearing Account
        - ra = User.revenue_clearing_account_balance
        td class="#{ra != 0 ? "error-amount" : ""}" = ra
      tr
        td Invoices Nums (PMS)
        td = pms_size
      tr
        td Invoices TotalAmount (PMS)
        - pms_amount = @base_invoices.sum(&:total_receivable).round(2)
        td = to_currency pms_amount
      tr
        td Invoices Nums (QB)
        td = qb_size
      tr
        td Invoices TotalAmount (QB)
        - qb_amount = @qb_invoices.sum(&:amount).round(2)
        td = to_currency qb_amount
      tr
        td Counts Differs
        td Diff: #{pms_size - qb_size}
      tr
        td Amount Differs
        td = "Diff: #{to_currency (pms_amount - qb_amount).round(2)}"
  
    h3 Lost in PMS or Error Amount
    table class=table_base_class 
      - diff_in_pms_invoice_id = (@qb_invoices.map(&:local_value) - @pms_invoice_ids.map(&:to_s)).uniq
      tr.theader
        td ID
        td InvoiceDate
        td Amount
      - @qb_invoices.where(local_value: diff_in_pms_invoice_id).each do |qbin|
        - if current_user.debugger?
          tr.none: td = qbin.qb_json
        tr
          td = qbin.local_value
          td = qbin.finance_date
          td = qbin.finance_amount
  .gap
  .right-panel style="width: 62%"
    h3 Lost in QB or Error Amount
    table class=table_base_class 
      tr.theader
        td Invoice No.
        td Status
        td Amount
        td AmountInQB
        td LateFee
        td Diff
        td LastSync
        td Booking ID
      - @base_invoices.includes(:booking).each do |invoice|
        - invoice_in_qb = @qb_invoices.find{|a| a.invoice_id.to_s == invoice.id.to_s}
        - compare_class = ""
        - compare_class = "lost-inqb" if !invoice_in_qb
        - compare_class = "error-amount" if invoice_in_qb && (invoice.total_receivable.to_s != invoice_in_qb.amount.to_s)
        - if compare_class.presence
          tr class=compare_class
            td = invoice.id
            td = invoice.status
            - aa = invoice.total_receivable || 0
            td = to_currency aa
            - ab = invoice_in_qb&.amount || 0
            td = to_currency ab
            td = invoice.late_fee
            td = to_currency (aa - ab).round(2).abs
            td = invoice_in_qb&.last_sync
            td = [invoice.booking_id, invoice.booking&.status].join(": ")

app/views/home/compare_journal_entries.html.slim
- pms_je_nos = @pms_jes.map(&:journal_no).uniq
- qb_je_nos = @qb_jes.map(&:local_value).uniq
.main-content
  .left-panel
    h3 = "Compares (Diff: #{pms_je_nos.size - qb_je_nos.size})"
    table class=table_base_class 
      tr
        td JournalEntries Nums(PMS)
        td = pms_je_nos.size
      tr
        td JournalEntries TotalAmount(PMS)
        td = @pms_jes.sum(&:amount).round(2)
      tr
        td JournalEntries Nums(QB)
        td = qb_je_nos.size
      tr
        td JournalEntries TotalAmount(QB)
        td = @qb_jes.sum(&:amount).round(2)

    h3 Lost in PMS or diff Date
    table class=table_base_class
      - diff_in_pms_je_ids = (@qb_jes.map(&:local_value) - pms_je_nos).uniq
      tr.theader
        td JE No
        td Journal Date(QB)
        td Journal Date(PMS)
        td Amount
      - _jes = JournalEntry.where(journal_no: diff_in_pms_je_ids)
      - @qb_jes.where(local_value: diff_in_pms_je_ids).each do |qbje|
        - if current_user.debugger?
          tr.none: td = qbje.qb_json
        tr
          td = qbje.local_value
          td = qbje.finance_date
          td = _jes.find{|a|a.journal_no == qbje.local_value}&.journal_date
          td = qbje.finance_amount
  .gap
  .right-panel
    h3 Lost in QB or Error Amount
    table.left-table class=table_base_class
      tr
        td Journal No.
        td PMS Amount
        td QB Amount
        td Diff
        td ErrorMsg
      - @pms_jes.group_by(&:journal_no).each do |journal_no, jes|
        - qb_je = @qb_jes.find{|a| a.local_value == journal_no}
        - a = jes.sum(&:amount).round(2)
        - b = qb_je.amount.round(2) rescue 0
        - compare_class = ""
        - compare_class = "lost-inqb" if !qb_je
        - compare_class = "error-amount" if qb_je && a.to_s != b.to_s
        - if compare_class.presence
          tr class=compare_class
            td = journal_no
            td = a
            td = b
            td = (a-b).abs.round(2)
            td = compare_class

app/views/home/feishu_auth.html.slim
h3 Welcome
/.union_id = union_id = session[:feishu_user_union_id]
.info 
  table class="#{table_class}"
    - (@lark_user.extra.dig("user_info") || {}).each do |key, value|
      tr class="#{LarkApp::DisplayedFields.include?(key) ? "" : "hide"}"
        td = key
        td = value

app/views/home/forbidden.html.slim
.error Forbidden

app/views/home/index.html.slim
.main-content
  .top-panel
    h3 style="margin-left: 20px;"= "Rental Overview"
    .padding20
        / - cache "global_rental_overview", expires_in: 5.minutes do
        table class=table_base_class
          tr.theader
            td Year
            - DailyIncome::MonthMapper.each do |m|
              td = m
          - years_data = {}
          - 2014.upto(Time.now.year).to_a.reverse.each do |year|
            - years_data[year] = 0
            tr
              td.theader = link_to year, month_overview_path(period: year), target: "_blank"
              - end_month = year == Date.current.year ? Date.current.month : 12
              - 1.upto(end_month).each do |month|
                - range = year_month(year, month)
                - total = DailyIncome.rental_income.natural_month(range, "day").sum(&:total).round(2)
                - years_data[year] += total
                td = link_to to_currency(total), month_overview_path(period: range), target: "_blank"
  .bottom-panel
    .left-panel
      h3 = "Overview"
      - @chart_data = {\
        label: "Rental Overview",
        width: 500,\
        data: {\
          labels: years_data.keys.reverse,
          data: years_data.values.reverse,
        }\
      }
      = render "share/chart_bar"

    /.clear
    .right-panel style="float: right;"
      h3 = "Counts"
      table class=table_base_class 
        tr
          td House.active
          td = House.active_native_listings.count
        tr
          td Booking Count
          td = Booking.booked.count
        tr
          td Invoice Count
          td = AccountRecord.invoices.count
        tr
          td Due Unpaid Invoice Count (Recent 2 years)
          - c = Invoice.unpaid.due_over_2_years.size
          td 
            = link_to c, unpaid_invoices_path

app/views/home/jira_dashboard.html.erb
<style>
  table, td {
    border: 1px solid #bbb;
  }
</style>
<table>
  <tr>
    <th> Status </th>
    <th> Task </th>
    <th> Assignee </th>
    <th> Reporter </th>
    <th> 预计上线时间</th>
  </tr>
  <% @tasks.each do |jt|  %>
    <tr>
      <td class='center'> <%= jt.status %> </td>
      <td> <%= jt.basic_lark_title %> </td>
      <td> <%= jt.short_assignee %> </td>
      <td> <%= jt.reporters.join(",") %> </td>
      <td> <%= jt.release_date %> </td>
    </tr>
  <% end %>
</table>